name: Website

on: 
  workflow_dispatch:
  push:
    branches:
      - main
#      - staging
# 'staging' branch now exists

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'    
    - name: Build Jekyll Pages
      run: |
        NOKOGIRI_USE_SYSTEM_LIBRARIES=true bundle install
        github-pages build
    - name: GCP Login
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Publish to GCS
      # run: gsutil rsync -d -r _site ${{ secrets.GCS_BUCKET_main }}
      run: gsutil rsync -d -r _site ${{ secrets.GCS_BUCKET_staging }}
# need to figure out how to concat the branch name ('main' or 'staging') with the secret name

