name: Website

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - staging
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set branch specific variables
      id: environment
      run: |
        if [[ "${GITHUB_REF#refs/heads/}" =~ (main|staging) ]]; then
          echo "::set-output name=BRANCH_SPECIFIC_BUCKET_NAME::GCS_BUCKET_${GITHUB_REF#refs/heads/}"
        else
          echo "::set-output name=BRANCH_SPECIFIC_BUCKET_NAME::GCS_BUCKET_staging"
        fi
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'    
    - name: Build Jekyll Pages
      run: |
        NOKOGIRI_USE_SYSTEM_LIBRARIES=true bundle install
        github-pages build
    - name: GCP L
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Publish to GCS
      run: gsutil rsync -d -r _site ${{ secrets[steps.environment.outputs.BRANCH_SPECIFIC_BUCKET_NAME] }}
